### ISSUE TITLE
Examples fail to build

### ISSUE THREAD

**Issue by suhasHere** [BiagioFesta/wtransport-examples#1]
Hi, I am new to rust and trying out the examples for webtransport. 
The examples as defined today doesn't seem to successfully build . please see below

error[E0432]: unresolved import `wtransport::connection::Connecting`
 --> utilities/src/webtransport_server.rs:7:5
  |
7 | use wtransport::connection::Connecting;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^----------
  |     |                       |
  |     |                       help: a similar name exists in the module: `Connection`
  |     no `Connecting` in `connection`

error[E0308]: mismatched types
  --> utilities/src/webtransport_server.rs:32:37
   |
32 |     let endpoint = Endpoint::server(config).context("Cannot build WebTransport endpoint")?;
   |                    ---------------- ^^^^^^ expected `ServerConfig`, found `ServerConfigBuilder<WantsTransportConfigServer>`
   |                    |
   |                    arguments to this function are incorrect
   |
   = note: expected struct `wtransport::ServerConfig`
              found struct `ServerConfigBuilder<WantsTransportConfigServer>`
note: associated function defined here
  --> /Users/snk/.cargo/git/checkouts/wtransport-0fc0bd2463eb0cbe/705fbd7/wtransport/src/endpoint.rs:83:12
   |
83 |     pub fn server(server_config: ServerConfig) -> std::io::Result<Self> {
   |            ^^^^^^

error[E0599]: no method named `context` found for struct `IncomingSession` in the current scope
  --> utilities/src/webtransport_server.rs:35:59
   |
35 |         let incoming_connection = endpoint.accept().await.context("Endpoint failed")?;
   |                                                           ^^^^^^^ method not found in `IncomingSession`

error[E0618]: expected function, found `F`
  --> utilities/src/webtransport_server.rs:36:22
   |
16 |     connection_handler: F,
   |     ------------------ `connection_handler` has type `F`
...
36 |         tokio::spawn(connection_handler(incoming_connection));
   |                      ^^^^^^^^^^^^^^^^^^---------------------
   |                      |
   |                      call expression requires function

**Comment by BiagioFesta** [comment]
Hi,
At the moment, I am not actively maintaining this repository. That's because I am planning to move/create new example directly in the [`wtransport`](https://github.com/BiagioFesta/wtransport) project.

For now, I should have fixed the issue with [this](https://github.com/BiagioFesta/wtransport-examples/commit/4d2f15459097622409cafd49cd618cd8083ecaae) commit (pushed in `main` branch a few moments ago).

Having said that,
I would anyway suggest you to have a look at `wtransport` examples [here](https://github.com/BiagioFesta/wtransport/tree/master/wtransport/examples). Those are the "official" `wtransport` example in the repository. Very simple and minimal, but it is a good starting template for a client and a server
