### ISSUE TITLE
Program exists as soon as compiles and runs every time I run

### ISSUE THREAD

**Issue by pylearndl** [BiagioFesta/wtransport-examples#2]
Hi,

I'm fairly new in rust. I just tried to run your code but come across the issue that program exists as soon as compiles and runs.

Why rust code abruptly exits I run the code in RustRover and cmd command prompt. Everytime prints one line for certificate fingerprint and exits automatically!

Certificate fingerprint: N93Ifa9Jgj7TW9PygvzGLtL47gNAhYGfZpMGQ9khniE=

Please see screenshots. How to solve it? Please help

![image](https://github.com/BiagioFesta/wtransport-examples/assets/46265022/8991b40d-ae28-4df8-8623-cd10a6ed07d5)

![image](https://github.com/BiagioFesta/wtransport-examples/assets/46265022/ed192bc3-daec-4671-89df-26ffb494a66a)

![image](https://github.com/BiagioFesta/wtransport-examples/assets/46265022/14198d76-2ffb-4e00-887c-84bea7f6df48)

**Comment by BiagioFesta** [comment]
Hi,
sorry for the late reply but I was off for a while without internet connection available.

Those examples (this very repository -`wtransport-examples`-) are not very well maintainer because I ported examples directly in the main repository: [see wtransport/examples](https://github.com/BiagioFesta/wtransport/tree/master/wtransport/examples).

If you want to start with webtransport I would recommend to start from the `example/full.rs`

Just getting started with the main `README.md`: [here](https://github.com/BiagioFesta/wtransport#getting-started) 

If you have any trouble, please feel free to drop an issue on the main repository (probably I am going to delete this one)

**Comment by pylearndl** [comment]
> Hi, sorry for the late reply but I was off for a while without internet connection available.
> 
> Those examples (this very repository -`wtransport-examples`-) are not very well maintainer because I ported examples directly in the main repository: [see wtransport/examples](https://github.com/BiagioFesta/wtransport/tree/master/wtransport/examples).
> 
> If you want to start with webtransport I would recommend to start from the `example/full.rs`
> 
> Just getting started with the main `README.md`: [here](https://github.com/BiagioFesta/wtransport#getting-started)
> 
> If you have any trouble, please feel free to drop an issue on the main repository (probably I am going to delete this one)

Hi,
Thanks for the reply. `wtransport-examples/example/full.rs`  works fine. I wanted to try `mediaoverweb` from `[wtransport-examples](https://github.com/BiagioFesta/wtransport-examples)`. I'm just beginner in Rust and have no idea how to move `mediaoverweb` codes to  `wtransport-examples/example/full.rs` just to try send video on webtransport. I'm trying to do that by learning from your both repositories codes by going through line by line. Please let me know if there's more convenience way to do it. Cheers

**Comment by BiagioFesta** [comment]
I see, unfortunately I am not actively maintaining `mediaoverweb`/`8bytesmsg` examples, but we could try to see if we can solve the issue.

Considering the example is exiting without any output, can you try to run the `8bytesmsg` binary ensuring all instance of google chrome are closed?

**Comment by BiagioFesta** [comment]
I made a big refactoring and pushed on `master` branch: https://github.com/BiagioFesta/wtransport-examples/commit/480b63f7cf86c57047044145d2e4ef77ee078061

Please pull recent commit and try again `cargo run --release`

**Comment by pylearndl** [comment]
@BiagioFesta Fantastic help mate. `WTransport-Examples-mediaoverweb` connect to webtransport works flawlessly on https://127.0.0.1:4433
I can not thank you enough. Your help encouraged me more to learn Rust/webtransport. 
Also, I successfully transferred the code from your repository old `mediaoverweb` to `wtransport-examples/example/full.rs` and it gave me the same result on http://localhost:8080/
Thank you again. I'll reach out to you if I need further help. Cheers

**Comment by BiagioFesta** [comment]
Glad it worked!

Feel free to reach out again; cheers and happy rust-coding! :)

**Comment by pylearndl** [comment]
@BiagioFesta How can I send continues data, received from bidirectional stream like echo server using bidirectional?
I tried to echo but server closes the bidi-stream as soon as server sends first data received. I used this code to echo but closes the stream as soon as finish sending.
`loop {
        tokio::select! {
            stream = connection.accept_bi() => {
                let mut stream = stream?;
                let bytes_read = match stream.1.read(&mut buffer).await? {
                    Some(bytes_read) => bytes_read,
                    None => continue,
                };

                stream.0.write(&buffer[..bytes_read]).await?;
            }
        }
    }`

**Comment by BiagioFesta** [comment]
From what I can deduct from your code snippet:
* `stream` is a variable scoped in the `tokio::select`. *Generally*, in rust when a variable goes out of scope the object destructor is called (so resources are deallocated). In your snippet, after `stream.0.write` the `stream` variable is destroyed (the `{ }` block ends) and so the stream is closed.

Example:
```rust
fn foo(connection: Connection) { 
   // ... some code here...

   {  // Now I open a scope with curly bracket
         let mut stream = connection.accept_bi().await.unwrap();
         stream.0.write(b"ciao").await.unwrap();
    }   // the scope ends so the `stream` goes out of scope and the destructor is called; so the stream is automatically ended
}
```

So if you want to keep the stream opened you need to keep `stream` variable "alive". It depends on your program.

For example you can store each stream inside a collection of streams; but it really depends on the context.

* You might want to consider to use [`write_all`](https://docs.rs/wtransport/latest/wtransport/struct.SendStream.html#method.write_all) (instead of `write`). 
   * `write_all` awaits until ALL bytes are queue in the send-buffer.
   * `write` might not write the entire bytes, indeed it returns the number of bytes sent (they might be less than your input buffer, because of flow-controller)

**Comment by BiagioFesta** [comment]
In general, there are many resources about learning rust around there.

The official resource (if you don't have already): https://doc.rust-lang.org/book/

**Comment by pylearndl** [comment]
@BiagioFesta Thanks. I'll try your solutions. I'm also went half way through the book you have suggested, and now got paper book The Rust Programing Langauge 2nd Edition. Cheers
